name: Ruff Linter

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Note: v4 is the current standard
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install the code linting and formatting tool Ruff
        run: pipx install ruff

      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py39
        # If this fails, the job is marked as "Failed", but...

      - name: Check code formatting with Ruff
        # ...this line ensures this step runs anyway!
        if: success() || failure()
        run: ruff format --diff --target-version=py39
